[package]
name = "imgui-sfml-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.11.0"
imgui-opengl-renderer = "0.12.1"
sfml = "0.21.0"

